eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 
      
spring:
  cloud:
    gateway:    
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: catalogo-produto-api
          uri: lb://CATALOGO-PRODUTO-API
          predicates:
            - Path=/produtos/**
        - id: carrinho-compras-api
          uri: lb://CARRINHO-COMPRAS-API
          predicates:
            - Path=/carrinho/**
